;; hide the menu bar
(menu-bar-mode -1)

;; mode line
(setq-default mode-line-format
              '("%e"
                " %* %b %l:%c"
                (vc-mode vc-mode)
                " "
                mode-line-modes
                mode-line-misc-info))

(apply 'custom-set-faces
       (let ((base03 "#002B36")
             (base02 "#073642")
             (base01 "#586E75")
             (base00 "#657B83")
             (base0 "#839496")
             (base1 "#93A1A1")
             (base2 "#EEE8D5")
             (base3 "#FDF6E3")
             (yellow "#B58900")
             (orange "#CB4B16")
             (red "#DC322F")
             (magenta "#D33682")
             (violet "#6C71C4")
             (blue "#268BD2")
             (cyan "#2AA198")
             (green "#859900"))
         `(;; basic
           (default ((t (:inherit unspecified))))
           (cursor ((t (:inherit unspecified))))
           (shadow ((t(:foreground ,base01))))
           (link ((t (:foreground ,violet :underline t))))
           (link-visited ((t (:foreground ,magenta :underline t))))
           (match ((t (:foreground ,yellow :inverse-video t))))
           (error ((t (:foreground ,red :inverse-video t))))
           (warning ((t (:foreground ,red))))
           (success ((t (:foreground ,blue))))
           (escape-glyph-face ((t (:foreground ,red))))
           (fringe ((t (:foreground ,base01))))
           (linum ((t (:foreground ,base01 :underline nil :inverse-video nil))))
           (highlight ((t (:background ,base02))))
           (hl-line ((t (:background ,base02))))
           (isearch ((t (:foreground ,orange :background ,base03 :inverse-video t))))
           (isearch-fail ((t (:inherit error))))
           (lazy-highlight ((t (:inherit match))))
           (menu ((t (:foreground ,base0 :background ,base02))))
           (minibuffer-prompt ((t (:foreground ,cyan))))
           (region ((t (:foreground ,base01 :background ,base03 :inverse-video t))))
           (secondary-selection ((t (:background ,base02))))
           (trailing-whitespace ((t (:foreground ,red :inverse-video t))))
           (vertical-border ((t (:foreground ,base01))))
           ;; custom
           (custom-button ((t (:foreground ,base1 :background ,base02))))
           (custom-button-mouse ((t (:inherit custom-button :inverse-video t))))
           (custom-button-pressed ((t (:inherit custom-button-mouse))))
           (custom-changed ((t (:foreground ,blue :background ,base3 :inverse-video t))))
           (custom-comment ((t (:foreground ,base1 :background ,base02))))
           (custom-comment-tag ((t (:foreground ,base1 :background ,base02))))
           (custom-documentation ((t (:inherit default))))
           (custom-group-tag ((t (:foreground ,base1))))
           (custom-group-tag-1 ((t (:inherit custom-group-tag))))
           (custom-invalid ((t (:foreground ,red :inverse-video t))))
           (custom-link ((t (:foreground ,violet))))
           (custom-state ((t (:foreground ,green))))
           (custom-variable-tag ((t (:foreground ,base1))))
           ;; font-lock
           (font-lock-builtin-face ((t (:foreground ,green))))
           (font-lock-comment-face ((t (:foreground ,base01))))
           (font-lock-constant-face ((t (:foreground ,cyan))))
           (font-lock-function-name-face ((t (:foreground ,blue))))
           (font-lock-keyword-face ((t (:foreground ,green))))
           (font-lock-string-face ((t (:foreground ,cyan))))
           (font-lock-type-face ((t (:foreground ,yellow))))
           (font-lock-variable-name-face ((t (:foreground ,blue))))
           (font-lock-warning-face ((t (:foreground ,red))))
           (font-lock-doc-face ((t (:foreground ,base01))))
           (font-lock-doc-string-face ((t (:foreground ,base01))))
           (font-lock-color-constant-face ((t (:foreground ,green))))
           (font-lock-comment-delimiter-face ((t (:foreground ,base01))))
           (font-lock-preprocessor-face ((t (:foreground ,orange))))
           (font-lock-reference-face ((t (:foreground ,cyan))))
           (font-lock-negation-char-face ((t (:foreground ,red))))
           (font-lock-other-type-face ((t (:foreground ,blue))))
           (font-lock-regexp-grouping-construct ((t (:foreground ,orange))))
           (font-lock-special-keyword-face ((t (:foreground ,red))))
           (font-lock-exit-face ((t (:foreground ,red))))
           (font-lock-other-emphasized-face ((t (:foreground ,violet))))
           (font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
           ;; show-paren
           (show-paren-match ((t (:foreground ,blue))))
           (show-paren-mismatch ((t (:foreground ,red))))
           ;; mode-line
           (mode-line ((t (:foreground ,base2 :background ,orange))))
           (mode-line-inactive ((t (:background ,base02))))
           (mode-line-buffer-id ((t (:inherit unspecified)))))))
